eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:61000/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 61002
spring:
  application:
    name: shisui-goods
  profiles:
    active: local
