eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:61000/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 61003
spring:
  application:
    name: shisui-auth
  profiles:
    active: local
shisui:
  ignoreUrl:
    - /V1/auth/getImageData
  userInfoIgnoreUrl:
    /V1/auth/getImageData

