spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shisui?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host:
#    port: 6379
#    password:
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.bigdata.order.entity.po
#showsql

#shisui:
#  ignoreUrl:
#    - /V1/auth/getImageData
#  userInfoIgnoreUrl:
#    /V1/auth/getImageData
